const data = [];
const createTask = document.querySelector('.Create');
const titleInput = document.querySelector('.Input-title'),
      dateInput = document.querySelector('.Input-date'),
      descriptionInput = document.querySelector('.Input-description'),
      resetButton = document.querySelector('.Reset');
const editModal = document.querySelector('.modal'),
      modalClose = document.querySelector('.modalClose'),
      editTitle = document.querySelector('.editTitle'),
      editDescription = document.querySelector('.editDescription'),
      editDate = document.querySelector('.editDate'),
      modalCheckbox = document.querySelector('.modalCheckbox>input'),
      modalChange = document.querySelector('.Change'),
      modalContent = document.querySelector('.modalContent');
const closeTask = document.querySelector('.closeTask__modal'),
      closePopupBtn = document.querySelector('.closePopup'),
      cancelDeleteTask = document.querySelector('.cancel'),
      confirmDeleteTask = document.querySelector('.OK');
